--------------------------------------------------------
-- Archivo creado  - viernes-mayo-15-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ARTICULOS_OBJ
--------------------------------------------------------

  CREATE TABLE "JONARANJO"."ARTICULOS_OBJ" OF "JONARANJO"."T_ARTICULO" 
   (	SCOPE FOR ("REF_FAMILIA") IS "JONARANJO"."FAMILIAS_OBJ" 
   ) OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" 
 NESTED TABLE "LIST_REF_T_COMPONENTE" STORE AS "LCOMPONENTESNTAB"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ) RETURN AS VALUE;
--------------------------------------------------------
--  DDL for Index ARTICULOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JONARANJO"."ARTICULOS_PK" ON "JONARANJO"."ARTICULOS_OBJ" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0022419
--------------------------------------------------------

  CREATE UNIQUE INDEX "JONARANJO"."SYS_C0022419" ON "JONARANJO"."ARTICULOS_OBJ" ("SYS_NC0001300014$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0022420
--------------------------------------------------------

  CREATE UNIQUE INDEX "JONARANJO"."SYS_C0022420" ON "JONARANJO"."ARTICULOS_OBJ" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ;
--------------------------------------------------------
--  Constraints for Table ARTICULOS_OBJ
--------------------------------------------------------

  ALTER TABLE "JONARANJO"."ARTICULOS_OBJ" MODIFY ("CODIGO" NOT NULL ENABLE);
  ALTER TABLE "JONARANJO"."ARTICULOS_OBJ" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "JONARANJO"."ARTICULOS_OBJ" MODIFY ("CANTMINIMA" NOT NULL ENABLE);
  ALTER TABLE "JONARANJO"."ARTICULOS_OBJ" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "JONARANJO"."ARTICULOS_OBJ" MODIFY ("REF_FAMILIA" NOT NULL ENABLE);
  ALTER TABLE "JONARANJO"."ARTICULOS_OBJ" ADD CONSTRAINT "ARTICULOS_PK" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO"  ENABLE;
  ALTER TABLE "JONARANJO"."ARTICULOS_OBJ" ADD UNIQUE ("LIST_REF_T_COMPONENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO"  ENABLE;
  ALTER TABLE "JONARANJO"."ARTICULOS_OBJ" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ARTICULOS_OBJ
--------------------------------------------------------

  ALTER TABLE "JONARANJO"."ARTICULOS_OBJ" ADD CONSTRAINT "ARTICULOS_FAMILIAS_FK" FOREIGN KEY ("REF_FAMILIA")
	  REFERENCES "JONARANJO"."FAMILIAS_OBJ"  ENABLE;
